name: Cleanup AWS Residuals
description: Deletes orphaned ENIs, releases Elastic IPs, and detaches Internet Gateways from a given VPC

inputs:
  vpc_id:
    description: "The VPC ID to clean up"
    required: true

runs:
  using: "composite"
  steps:
    - name: 🧼 Delete ENIs and release EIPs
      shell: bash
      run: |
        echo "Cleaning up resources for VPC: ${{ inputs.vpc_id }}"

        # Delete ENIs
        ENIs=$(aws ec2 describe-network-interfaces \
          --filters "Name=vpc-id,Values=${{ inputs.vpc_id }}" \
          --query "NetworkInterfaces[*].NetworkInterfaceId" --output text)

        if [ -n "$ENIs" ]; then
          for eni in $ENIs; do
            echo "→ Deleting ENI: $eni"
            aws ec2 delete-network-interface --network-interface-id $eni || true
          done
        else
          echo "✅ No residual ENIs found."
        fi

        # Release Elastic IPs
        EIPs=$(aws ec2 describe-addresses \
          --query "Addresses[*].AllocationId" --output text)

        if [ -n "$EIPs" ]; then
          for eip in $EIPs; do
            echo "→ Releasing EIP: $eip"
            aws ec2 release-address --allocation-id $eip || true
          done
        else
          echo "✅ No orphaned EIPs found."
        fi

        # Detach Internet Gateways
        IGWS=$(aws ec2 describe-internet-gateways \
          --filters "Name=attachment.vpc-id,Values=${{ inputs.vpc_id }}" \
          --query "InternetGateways[*].InternetGatewayId" --output text)

        if [ -n "$IGWS" ]; then
          for igw in $IGWS; do
            echo "→ Detaching IGW: $igw"
            aws ec2 detach-internet-gateway --internet-gateway-id $igw --vpc-id ${{ inputs.vpc_id }} || true
          done
        else
          echo "✅ No attached Internet Gateways found."
        fi

        echo "✅ Residual cleanup complete. Waiting for AWS to settle..."
        sleep 30
