apiVersion: v1
kind: Service
metadata:
  name: ghs-service
  namespace: coweb-ns
  labels:
    app: ghs-web
spec:
  type: LoadBalancer
  selector:
    app: ghs-web
  ports:
    - port: 80
      targetPort: 80

