apiVersion: v1
kind: Namespace
metadata:
  name: coweb-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghs-web
  namespace: coweb-ns
  labels:
    app: ghs-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ghs-web
  template:
    metadata:
      labels:
        app: ghs-web
    spec:
      containers:
        - name: my-web-app
          image: 160002177953.dkr.ecr.eu-west-2.amazonaws.com/ghs-nginx-app46:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"

